### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ttyieu** [i18next/i18next-express-middleware#10]
So, according to the README, function `middleware.getResourcesHandler` is supposed to be used like this:
```javascript
app.get('/locales/resources.json', middleware.getResourcesHandler(i18next))
```
If I understand it right, the params for `lng` and `ns` have to be set through the query string, because this function reads them from `req.query`. But when these params are not passed, the function throws an error:
```
TypeError: Cannot read property 'split' of undefined
   at /usr/src/node_modules/i18next-express-middleware/lib/index.js:114:57
```
Shouldn't it at least check first if the params are set?
And more importantly, why can't we read the language from `req.lng` or `req.params.lng` here, as it is in the rest of the module?

**Comment by jamuhl** [comment]
1) right: will add the check
2) this route is not for internal use - but is used to get resources down to the client (browser). The browser can request any set of language, namespace combination.

**Comment by jamuhl** [comment]
check is in v0.3.1
