### ISSUE TITLE
Concurency with hbs helper 

### ISSUE THREAD

**Issue by adyz** [i18next/i18next-express-middleware#113]
Hi again, 

Looks like I have a problem with concurrency now.

When I do a load test, sometimes I get the wrong language.

I am not sure weather this is caused by the way I register the helper, the way my app flows or the way i18next changes the language.

Here is my code:

    
    /*
     * Included modules
     */
    
    var i18next = require('i18next');
    var i18next_middleware = require('i18next-express-middleware');
    var i18next_backend = require('i18next-node-remote-backend');
    var hbs = require('hbs');
    
    /*
     * Init i18next
     */
    
    i18next
        .use(i18next_middleware.LanguageDetector)
        .use(i18next_backend)
        .init({
            debug: false,
            preload: ['ro', 'bg', 'hu', 'hr', 'pl', 'sl', 'sk', 'cz'],
            fallbackLng: ['ro'],
            detection: {
                order: ['cookie', 'querystring']
            },
            backend: {
                loadPath: appShell.params.apiUrl + 'translate?key=all&&_format=json&language={{lng}}',
                crossDomain: true
            }
    
        });
    
    /*
     * Init express
     */
    
    var app = express();
    
    
    /*
     * Add middleware
     */
    
    app.use(i18next_middleware.handle(i18next, {
        ignoreRoutes: ['favicon.ico','css/', 'js/', 'images/'],
        removeLngFromUrl: false
    }));
    
    /*
     * View engine setup
     */
    
    app.set('views', path.join(__dirname, './../common/templates'));
    app.set('view engine', 'hbs');
    
    
    /*
     * Wire up i18next to request object and register the helper
     */
    
    app.get('/', function(req, res, next){
        req.i18n.changeLanguage(req.language);

        //Register helper
        hbs.registerHelper('t', function(key) {
            return new hbs.SafeString(req.t(key));
        });
        next();
    });
    
    
    /*
     * Basic express render with a hbs template that has {{t 'translate.this.key.for.me'}}
     */
    
    app.use('/', require('./routes/home'));
    app.use('/', require('./routes/event'));
    app.use('/', require('./routes/product'));
    app.use('/cart', require('./routes/cart'));

Thanks for all your help

**Comment by adyz** [comment]
In my hbs file I have things like: `<h2>{{t 'view_tile_key'}}</h2>`

**Comment by jamuhl** [comment]
no need to call req.i18n.changeLanguage(req.language); in your route - that's the job of language detector

the problem each time you overwrite the hbs t helper with currents user language as the t function you get in req.t is fixed to user language

you will need to scope the hbs helper to the current request or use a hbs helper where you call i18n.t with options lng = req.lng

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-express-middleware/pull/1#issuecomment-160774474

**Comment by adyz** [comment]
Hm.... sounds good


    Handlebars.registerHelper('t', function() {
        var args = Array.prototype.slice.call(arguments);
        var options = args.pop();
        return i18next.t(args, {lng: options.data.root._locals.language});
    });

this looks like it's working, but not sure for the moment if this will perform well with memory and cpu, will investigate.

Thank you for all the help, a bit newbie to node and JS.
