### ISSUE TITLE
exposing dir() in jade templates

### ISSUE THREAD

**Issue by MartijnR** [i18next/i18next-express-middleware#12]
I'm wondering what is the recommend way to expose dir() in jade templates? I see the `req.i18n` object doesn't include a `dir()` method.

**Comment by jamuhl** [comment]
right req.i18n does not have all functions on it...but easy to add here: https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L41

You can provide a PR or i will add it asap.

**Comment by MartijnR** [comment]
Thanks! 

This helped me add it myself using:

**Comment by jamuhl** [comment]
in v0.3.0 you can `req.i18n.dir(lng)`

**Comment by MartijnR** [comment]
Great! Thanks
