### ISSUE TITLE
Changing Language doesn't work

### ISSUE THREAD

**Issue by jonaslund** [i18next/i18next-express-middleware#120]
Hi

Nice middleware!!

Question.

Trying to set the current language through this

```js
app.get("/lang/:lan?", function(req, res) {  
  let lan = req.params.lan;  
  req.i18n.changeLanguage(newlan);
...
```

But it doesn't work? 
This how I initialise i18n

```js
i18next
  .use(i18nextmiddleware.LanguageDetector)
  .use(filesystemBackend)
  .init({
    // debug: true,
    saveMissing: true,
    lngs: ['en', "pt", "pt-BR", "en-US"],
    load: 'all',
    fallbackLng : "en",
    backend: {
      loadPath: __dirname + '/locales/{{lng}}/{{ns}}.json'
    }
});
```  

what am I missing?

**Comment by jamuhl** [comment]
you might not need to use the languagedetector if setting it yourself - or remove you setting it and let the detector do its job: https://github.com/i18next/i18next-express-middleware#detector-options (enabling the path in order array)

**Comment by jonaslund** [comment]
I was misunderstanding the logic, and thought that   
```js  
req.i18n.changeLanguage(newlan);
```
would set the language and keep it in a session, which is not the default behaviour, and the
```js
  req.i18n.changeLanguage(newlan);
```
needs to be called directly before rendering any output
