### ISSUE TITLE
The "examples" folder...

### ISSUE THREAD

**Issue by minimok** [i18next/i18next-express-middleware#121]
...is missing :-)

**Comment by jamuhl** [comment]
not missing...there is just no example ;)

**Comment by jamuhl** [comment]
```
var i18next = require('i18next');
var middleware = require('i18next-express-middleware');
var express = require('express');

i18next
  .use(middleware.LanguageDetector)
  .init(i18nextOptions);

var app = express();
app.use(middleware.handle(i18next, {
  ignoreRoutes: ["/foo"],
  removeLngFromUrl: false
}));


// in your request handler
app.get('myRoute', function(req, res) {
  var lng = req.language; // 'de-CH'
  var lngs = req.languages; // ['de-CH', 'de', 'en']
  req.i18n.changeLanguage('en'); // will not load that!!! assert it was preloaded

  var exists = req.i18n.exists('myKey');
  var translation = req.t('myKey');
});

// in your views, eg. in jade
div=t('myKey')
```

**Comment by minimok** [comment]
Thx. I've been playing with those, with no success. I'm trying to upgrade from the old i18next-node (1.7.1) which worked perfectly. Nearly everything works...apart from actual translation :-)
The issue seems to be the filesystem-backend part. I'll see what happens if I swap that ut for something else.

**Comment by jamuhl** [comment]
you're using https://github.com/i18next/i18next-node-fs-backend ?!?

**Comment by jamuhl** [comment]
https://www.youtube.com/watch?v=uO30Jm8TSy4&sns=tw

or use http://locize.com instead of your own backend ;)

using locize directly supports the future of i18next.

**Comment by minimok** [comment]
yep...using 18next/i18next-node-fs-backend

Managed to fix it - it seems to prefer its options in json format. 

Locize looks interesting. I'll take a look.
