### ISSUE TITLE
default language without the detector 

### ISSUE THREAD

**Issue by emauricio** [i18next/i18next-express-middleware#122]
Hi, 

Im not sure if this is a bug or just using it in the wrong way. 😝 

Im trying to set the default languge (no need for detection) but somehow  is being asigning  by the `req.lng` or `i18next.services.languageUtils`, but then is missing to check if 'i18next' have a default `lng`

**Comment by jamuhl** [comment]
please paste your config - so i could check if there is some missconfiguration. thank you.

**Comment by emauricio** [comment]
this is what i set.

```
const defaultOptions: any = {
            debug: false,
            lng: 'ja'
            load: 'languageOnly',
            fallbackLng: 'en',
            backend: {
                loadPath: 'locales/{{lng}}/{{ns}}.json'
            }
        };

        i18next.use(FilesystemBackend)
            .use(sprintf)
            .init(defaultOptions);

app.use(i18nextMiddleware.handle(i18next, {
            ignoreRoutes: ['/static']
        }));
```

**Comment by jamuhl** [comment]
looks ok to me. not using language detection you will need to set language on request - not on the i18next instance:

```
const defaultOptions: any = {
            debug: true,
            lng: 'ja'
            load: 'languageOnly',
            fallbackLng: 'en',
            backend: {
                loadPath: 'locales/{{lng}}/{{ns}}.json'
            }
        };

        i18next.use(FilesystemBackend)
            .use(sprintf)
            .init(defaultOptions);

// here:
app.use((req, res, next) => {
  req.lng = 'ja';
  next();
});

app.use(i18nextMiddleware.handle(i18next, {
            ignoreRoutes: ['/static']
        }));
```

**Comment by jamuhl** [comment]
As language is set per request...not per server instance of i18next

**Comment by emauricio** [comment]
ahh thx, at the moment im doing it like that, but it give me the feeling that it was a workaround, so i was wondering if there was something worng with my settings.
since in the documentation says `lng: language to set (disables user language detection)`

then in this way is kind of forced in the request instead of the setting, what will be the pourpose for lng in the i18next instance? 

thank you so much for your time.

**Comment by jamuhl** [comment]
the lng in the i18next instance...basically that has no value...but for reasons will be set in middleware to the language set in request...so it would be semi-safe to be used eg. in other modules during the request (semi-safe as only true as long operations are done sync - which is not what you will do).

 the documentation statement is more for the usecase on clientside - where setting language remove detection - in express the stuff is different - as all is built around a req, res -> async and lng has to be set per request basis.

**Comment by emauricio** [comment]
got it, thank you again. have a great weekend. 😃

**Comment by jamuhl** [comment]
same for you...happy coding.

And if ever needing some translation management on top of i18next - remember there is http.//locize.com (our extra service tier on top of i18next)
