### ISSUE TITLE
localized routes

### ISSUE THREAD

**Issue by mapb1990** [i18next/i18next-express-middleware#123]
hi,

I'm try create one localation route '/:lng/route.one' but without success. when I try to access  the following urls, I'm getting 'Cannot GET /en/route1-en'

http://localhost:3000/en/route1-en
http://localhost:3000/th/route1-th

**app.js**
```javascript
// Set localization
let i18nextOptions = {
    debug: true,
    // lng: 'en',
    fallbackLng: "th",
    backend: {
        loadPath: "locales/{{lng}}/{{ns}}.json"
    },
    ns: ["general"],
    defaultNS: "general",
    fallbackNS: "general",
    detection: {
       order: ['path', 'session', 'querystring', 'cookie', 'header']
    },
};

i18next
    .use(i18nFileSystem)
    .use(i18nMiddleware.LanguageDetector)
    .init(i18nextOptions, function() {
        i18nMiddleware.addRoute(i18next, '/:lng/route.one', ['en', 'th'], app, 'get', function(request, response) {
            response.send(`<pre>req: ${request.language} i18next: ${i18next.language}\n
            keys:\n${i18next.t('key1')}
${i18next.t('key2')}
${i18next.t('key3')}
${i18next.t('key4')} `);
        });

app.use(i18nMiddleware.handle(i18next, {
  removeLngFromUrl: false
}));
```

**locales/en/general.json**
```javascript
{
  "hello-world": "Hello World",
  "key1": "value of key 1 in en",
  "key2": "value of key 2 in en",
  "key3": "value of key 3 in en",
  "route": {
    "one": "route1-en",
    "two": "route2-en"
  },
}
```

**locales/th/general.json**
```javascript
{
  "hello-world": "Hello World in TH",
  "key1": "value of key 1 in th",
  "key2": "value of key 2 in th",
  "route": {
    "one": "route1-th",
    "two": "route2-th"
  }
}
```

**Comment by jamuhl** [comment]
config looks ok to...worked last time i checked...not sure something changed that breaks your code?

might find the time to check later...

**Comment by jamuhl** [comment]
try adding `preload: ['en', 'th']` to i18next.init options

**Comment by mapb1990** [comment]
same result

```javascript
let i18nextOptions = {
    debug: true,
    // lng: 'en',
    fallbackLng: "th",
    preload: ['en', 'th'],
    backend: {
        loadPath: "../locales/{{lng}}/{{ns}}.json"
    },
    ns: ["general"],
    defaultNS: "general",
    fallbackNS: "general",
    detection: {
       order: ['path', 'session', 'querystring', 'cookie', 'header'],
    },
};

```

**Comment by jamuhl** [comment]
hm...does the console.log state that the translations were loaded?

try console.log(i18next.services.resourceStore.data) on init callback:


```
i18next
    .use(i18nFileSystem)
    .use(i18nMiddleware.LanguageDetector)
    .init(i18nextOptions, function() {
console.log(i18next.services.resourceStore.data); // => does that output loaded data
        i18nMiddleware.addRoute(i18next, '/:lng/route.one', ['en', 'th'], app, 'get', function(request, response) {
            response.send(`<pre>req: ${request.language} i18next: ${i18next.language}\n
            keys:\n${i18next.t('key1')}
${i18next.t('key2')}
${i18next.t('key3')}
${i18next.t('key4')} `);
        });

```

if not loaded check the loadPath: might need to add `loadPath: path.join(__dirname, "../locales/{{lng}}/{{ns}}.json")`

**Comment by mapb1990** [comment]
I already managed to get it to work. I do not know what it was. I just reinstalled and it worked. weird. However now I have a new problem. When entering a route the translations are done for the default language and not for the language of the route.

on url ```/en/route1-en``` prints ```req: en i18next: undefined```

**Comment by jamuhl** [comment]
yes...the language gets not synced to the i18next main instance...as the language is fixed to current request. there is request.i18n https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L37 which is the request bound instance!

**Comment by mapb1990** [comment]
but the LanguageDetector should not be detect the language by path?

```javascript
    detection: {
       order: ['path', 'session', 'querystring', 'cookie', 'header'],
    },
```

**Comment by jamuhl** [comment]
yes but per request: detection happens inside the request on handle https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L20

on a cloned instance: https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L13 per request

if not done this way as soon as you have two requests doing async stuff - one fr the other en - both set lng on main instance of i18next -> the result would be mixed -> dangerous --> always use the t function, i18n instance of the current request

**Comment by jamuhl** [comment]
closing for now...feel free to reopen if still an issue / unclear
