### ISSUE TITLE
Bug while detecting language from path

### ISSUE THREAD

**Issue by varunest** [i18next/i18next-express-middleware#124]
For a url like "example.com/es" the detector is working fine. But if query params are added to the url then the detector fails, ex. "example.com/es?key=value". In this case it takes **es?key=value** as a language. 

I backtraced and found that issue is happening because in **path.js** we have this line : 

`var parts = req.originalUrl.split('/');
`
this should be 

`var parts = req.path.split('/');`

Can we please cross check and release a version with the fix. Thanks.

**Comment by jamuhl** [comment]
req.path is not reliable according to http://stackoverflow.com/questions/12525928/how-to-get-request-path-with-express-req-object

best option might be to split on `?` first and take that part[0] to split by `/`? what do you think?

**Comment by varunest** [comment]
Yes. That will do just fine.

**Comment by varunest** [comment]
Sorry for bothering you again, but any update on this?

**Comment by jamuhl** [comment]
no problem...will change that when i find time...if you like to speed this up you might submit a PR.

**Comment by varunest** [comment]
I have put a [PR](https://github.com/i18next/i18next-express-middleware/pull/125). Please cross check and merge.

**Comment by jamuhl** [comment]
merged and published.
