### ISSUE TITLE
cookie gets added twice

### ISSUE THREAD

**Issue by jamuhl** [i18next/i18next-express-middleware#127]
from switching to 1.0.4 to 1.0.5 , my server sends me two lines of cookies ...

Set-Cookie:i18next=fr; path=/; expires=Wed, 09 May 2018 12:43:34 GMT
Set-Cookie:i18next=fr; path=/; expires=Wed, 09 May 2018 12:43:34 GMT

... :s

**Comment by jamuhl** [comment]
https://github.com/pillarjs/cookies/pull/19/files overwrite flag should do the trick

**Comment by laurentdebricon** [comment]
Hello, 
indeed, putting 
 overwrite:true in setCookies works !

Looking forward for your next build :)

It's weird it looks like it's affecting only me, i thought i had a pretty basic config

```
  detection: {
      caches: ['cookie'],
      order: ['path', 'cookie', 'header'],
      lookupPath: 'lng'
    },
```

**Comment by jamuhl** [comment]
thanks for coming back to this...totally forgot about it.

updated and added the overwrite flag to cookie set.

published the update in i18next-express-middleware@1.0.6

would be great if you could check/review

**Comment by laurentdebricon** [comment]
it works great, thank you !

**Comment by jamuhl** [comment]
awesome...thank you for the feedback...and sorry again for the delay...really forgot this issue.
