### ISSUE TITLE
input check required.

### ISSUE THREAD

**Issue by GongT** [i18next/i18next-express-middleware#128]
I can manually set any string as a "sub" language (eg: zh-**notexists**).     
It will send to backend, no whitelist check.

I do no know how to describe this, there is a bug about "sub" language.

Test case:
```json
{ "whitelist": ["en", "zh“],  }
```
```json
{
"order": ["querystring", "cookie"],
"caches": ["cookie"],
"lookupQuerystring":"lng",
"lookupCookie":"i18n"
}
```

*I have a chrome plugin to change `Accept-Language`*

* set `lng=zh-xxxx`    
   server print "languageChanged: zh-xxxx"    
   backend create language file: zh-xxxx.json    
   return set-cookie: i18n=zh-xxxx

* set `lng=zhxxx`     
   server print "languageChanged: zh-xxxx"    
   return set-cookie: i18n=zh-xxxx

* clear cookies, set `lng=zhxxx`    
   server print "languageChanged: zh-cn"    
   backend create language file: zh-cn.json    
   return set-cookie: i18n=zh-cn

* clear cookies, set `lng=zhxxx`, set browser language=en-us    
   server print "languageChanged: en-us"    
   backend create language file: en-us.json    
   return set-cookie: i18n=en-us

* clear cookies, set `lng=zhxxx`, set browser language=en-xxxx    
   server print "languageChanged: en-xxxx"    
   backend create language file: en-xxxx.json    
   return set-cookie: i18n=en-xxxx

* clear cookies, set `lng=zhxxx`, set browser language=enxxx    
   server print "languageChanged: en"    
   return set-cookie: i18n=en
  
so there is no problem without the "-" in language.

**Comment by jamuhl** [comment]
i rather sure you mix something up...those results do not make any sense.

zhxxx - will be interpreted as language -> only can fallback to fallbackLng as not whitelisted
zh-xxx - will be treated as a regional variant of zh -> will be accepted and load `zh` an fallbackLng too

**Comment by jamuhl** [comment]
be aware...changeLanguage and setCookie do persist detected language - not the one finally used for translation (before whitelist) - same as i18next.language.

you find the used languages in order on i18next.languages or in middleware on `req.languages`

**Comment by GongT** [comment]
but `req.language` is `zh-xxx`, and fs backend will save new file `zh-xxx.json`

**Comment by GongT** [comment]
OK, I found the problem is caused by `nonExplicitWhitelist=true`,I miss understand this option. sorry waste your time...
