### ISSUE TITLE
bug in event listener of languageChanged

### ISSUE THREAD

**Issue by GongT** [i18next/i18next-express-middleware#129]
look at [this code](https://github.com/i18next/i18next-express-middleware/blob/a2e5b487ddb77f386ee5e705298d01e325f92873/src/index.js#L14)

It register a change event     
If option `caches: ['cookie']` is set, then set cookie.

There is no "off" call, so the resource will not release. I do not know if there is a memory leak. But I'm sure this will cause problem.

I have a api to hot-reload translate resource, by call `i18n.reloadResources(lng, ns);`.     
It will trigger `languageChange` event on all instance. *(why?)*     
If there are some response, header already sent, but data not complete sent.     
Then an error will thrown:
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:504:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at Cookies.set (/data/node_modules/cookies/lib/cookies.js:100:13)
    at Object.cacheUserLanguage (/data/node_modules/i18next-express-middleware/lib/languageLookups/cookie.js:42:15)
    at /data/node_modules/i18next-express-middleware/lib/LanguageDetector.js:127:119
    at Array.forEach (native)
    at LanguageDetector.cacheUserLanguage (/data/node_modules/i18next-express-middleware/lib/LanguageDetector.js:126:14)
    at /data/node_modules/i18next-express-middleware/lib/index.js:41:43
    at /data/node_modules/i18next/dist/commonjs/EventEmitter.js:52:18
    at Array.forEach (native)
    at I18n.emit (/data/node_modules/i18next/dist/commonjs/EventEmitter.js:51:14)
    at done (/data/node_modules/i18next/dist/commonjs/i18next.js:313:16)
    at Object.callback (/data/node_modules/i18next/dist/commonjs/i18next.js:333:9)
    at /data/node_modules/i18next/dist/commonjs/BackendConnector.js:152:13
    at Array.forEach (native)
    at Connector.loaded (/data/node_modules/i18next/dist/commonjs/BackendConnector.js:139:16)
```

**Comment by jamuhl** [comment]
Not sure...we have this in production for very long now...never saw a noticeable memory leak.

Not sure but reloadResources does not trigger changeLanguage: https://github.com/i18next/i18next/blob/master/src/i18next.js#L173

Until it does not finally fulfill some loading that was not done before by regular load. It would help a lot if you could provide a sample to reproduce. Hard to narrow down by just looking at the code.

**Comment by GongT** [comment]
there is too many code to paste here, the main idea is this:     
if I send a valid update request to `/editor/save`, soon after response success, an unhandled error will occur.

I have looked into `i18next-node-mongodb-backend` code, there is only one file, and only depend on `mongodb` package, no way to trigger a "languageChanged" event.

```
app.post('/editor/save', function (req, res, next) {
	const {ns, lng, value, path} = req.body;
	if (!value || !path) {
		throw new RequestError(STATUS_CODE.INVALID_INPUT, 'empty value');
	}
	
	languageDatabase.writeKey(lng, ns, path, value).then(() => {
		req.i18n.off('languageChanged'); // <------ will throw without this
		i18next.reloadResources(lng, ns); // <------ will not throw without this
		
		res.send({status: 0, message: 'ok'});
	}, next);
});

function writeKey(language, namespace, keyPath, value) {
	// use "mongodb" direct modify database used by "i18next-node-mongodb-backend"
	return this.update({
		language,
		namespace,
	}, {
		$set: {
			['data.' + keyPath]: value,
		},
	}, {
		upsert: true,
	});
}
```

**Comment by jamuhl** [comment]
the problem is reloadResources is really just useful in client where you like to reload but are not interested in when reloading is done (there is no callback). So that fires and your request will be closed before that is finished. To be useful in this scenario we would have to assert reload finished by providing a callback function.

easier would be to not rely on reload but just update the resource:

https://www.i18next.com/api.html#addresource

**Comment by GongT** [comment]
Yes, I can just use add resource, thanks!

**Comment by komcal** [comment]
@GongT Can you explain how you fix this bug? I use i18next with next.js and i got error `Error: Can't set headers after they are sent.` same as you.
