### ISSUE TITLE
middleware.LanguageDetector is undefined

### ISSUE THREAD

**Issue by TimoRuetten** [i18next/i18next-express-middleware#130]
`middleware.LanguageDetector` is undefined in my case. `middleware.handle` works fine.

Am I missing smth ?

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/example/nextjs/server.js#L16 we use that in the nextjs sample too...use it in production. hmm...do you have a older version...was not on our first release.

**Comment by TimoRuetten** [comment]
No - the problem was that I was using `import`. In this case only module.exports seems to be returned. I am now using `require` instead as like in your example. My fault!

**Comment by TimoRuetten** [comment]
To reproduce:

``` javascript
import middleware from 'i18next-express-middleware';
middleware. LanguageDetector; // undefined
```

``` javascript
var middleware = require('i18next-express-middleware');
middleware. LanguageDetector; // works
```

**Comment by jamuhl** [comment]
hm...yes...not yet updated to support import/export...might be time to do so...

**Comment by roonie007** [comment]
@jamuhl still no 'import' support ?
might be time to do so... 😛

**Comment by jamuhl** [comment]
@roonie007 haha...you're right...but honestly i do use this not enough to be high in my prios....feel free to do a PR...

**Comment by roonie007** [comment]
hihihihii so I checked your code , you have already implemented it , but it's not written in the readme or in any examples

it should work when it's used like this
```javascript
import { LanguageDetector } from 'i18next-express-middleware';

i18next
  .use(LanguageDetector)
  .use(Backend)
  .init({
```

**Comment by jamuhl** [comment]
seems like it...;)
