### ISSUE TITLE
@types/i18next-express-middleware typescript error

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next-express-middleware#132]
Hi...I've recently updated the defenitely type file of the i18next-express-middleware to the last version (0.0.31) and unfortunetly, I have a typescript error.

Here is the error I have:
```
[ts]
Argument of type 'i18n' is not assignable to parameter of type 'I18n'.
  Types of property 'init' are incompatible.
    Type '{ (options: InitOptions, callback?: Callback): i18n; (callback?: Callback): i18n; }' is not assignable to type '(options?: Options & ReactOptions, callback?: (err: any, t: TranslationFunction) => void) => I18n'.
      Types of parameters 'options' and 'options' are incompatible.
        Type 'Options & ReactOptions' is not assignable to type 'InitOptions'.
          Types of property 'load' are incompatible.
            Type 'string' is not assignable to type '"currentOnly" | "all" | "languageOnly"'
```

I didn't change my code at all..Just updated the types/i18next-express-middleware.

I looked up on your documentation and I'm doing exactly the same thing as described..

```
import * as i18next from 'i18next';
import * as i18nextMiddleware from 'i18next-express-middleware';
import * as express from 'express';
...
const i18nextOptions: i18next.InitOptions = {
  backend: {
    addPath: path.join(process.cwd(), 'language/static/{{lng}}/{{ns}}.missing.json'),
    jsonIndent: 2,
    loadPath: path.join(process.cwd(), 'language/static/{{lng}}/{{ns}}.json')},
  debug: false,
  defaultNS: 'My_Web_Server',
  fallbackLng: 'false',
  keySeparator: false,
  load: 'currentOnly',
  ns: 'My_Web_Server',
  nsSeparator: false,
  preload: ['es', 'fr', 'zh-Hans'],
  saveMissing: true,
  saveMissingTo: 'current',
  whitelist: ['fr', 'es', 'zh-Hans'],
};

i18next
  .use(i18nextBackend)
  .init(i18nextOptions);

const httpsApp = express();
httpsApp.use(i18nextMiddleware.handle(i18next, {removeLngFromUrl: false}));
```

I have the typescript error described earlier in the last line with `i18nextMiddleware.handle(i18next,`, directly on the i18next variable.

Am I doing something wrong or is it possible there is an issue in your definitly type file ?

Thank you for your help ...

**Comment by jamuhl** [comment]
i do not maintain the definitlytype files myself...so no idea if those are uptodate...sorry

**Comment by TitaneBoy** [comment]
Oh ...I see.. :-(.. Sorry for the inconvenience

**Comment by TitaneBoy** [comment]
@jamuhl ... Thanks for your quick answer...

Can you confirm me please if my code described before is correct anyway ?

Thank you

**Comment by jamuhl** [comment]
not sure...i believe the import statement for middleware could be not working...that library still exports commonjs only -> will need to update that i think.

that's why we need to https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/server.js#L11 

hopefully i get time to work on that after holiday...
