### ISSUE TITLE
`languageOnly` and `whitelist` ignored

### ISSUE THREAD

**Issue by tusbar** [i18next/i18next-express-middleware#139]
Hello,

I’m using the following configuration:

```js
i18n
  .use(fsBackend)
  .use(i18nextMiddleware.LanguageDetector)
  .init({
    fallbackLng: 'en',
    load: 'languageOnly',
    lowerCaseLng: true,

    ns: [
      'common',
      'home'
    ],
    defaultNS: 'common',
    whitelist: [
      'en', 'fr'
    ],

    preload: ['en', 'fr'],

    backend: {
      loadPath: path.join(__dirname, '../locales/{{lng}}/{{ns}}.json'),
      addPath: path.join(__dirname, '../locales/{{lng}}/{{ns}}.missing.json')
    },

    detection: {
      order: ['path', 'header']
    }
  })
```

Whenever I request a page without the `lng` set in the `path` (so it uses the `header` detector), `req.i18n.language` is `en-us`.

Why is that? Am I missing something? I’m expecting just `en`.

**Comment by jamuhl** [comment]
i18n.language reflects detected language -> i18n.languages (array) reflects what is used to lookup translations in order of priority https://www.i18next.com/api.html#language vs. https://www.i18next.com/api.html#languages

**Comment by tusbar** [comment]
Ah! I did miss something indeed. Thanks @jamuhl!

**Comment by Yankovsky** [comment]
I don't think that this issue is resolved.

My config:
```
{
  fallbackLng: 'en',
  load: 'languageOnly',
  detection: {
    order: ['path', 'cookie', 'header'],
    lookupCookie: 'language',
    lookupFromPathIndex: 0,
    caches: ['cookie'],
  }
}
```

Value of Accept-Language header is `en-US,en;q=0.9,ru;q=0.8`

Problem is in this part of code:
```
          var cleanedLng = _this.services.languageUtils.formatLanguageCode(lng);

          if (_this.services.languageUtils.isWhitelisted(cleanedLng)) {
            found = cleanedLng;
            req.i18nextLookupName = detectorName;
          };
```

In my case cleanedLng === 'en-US' and it becomes locale cached in cookies. But I asked just for language part via load: 'languageOnly' and whitelist. I want to get `en` as a language.

I checked source and I didn't find a way to change current external params or options.

**Comment by jamuhl** [comment]
this is solved in i18next core: https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L97

from the lng that was detected, it builds an array of languages to use for loading via backend and to lookup translations from internal resource store.
