### ISSUE TITLE
load multiple languages file

### ISSUE THREAD

**Issue by prtome** [i18next/i18next-express-middleware#14]
hello,
I seem to not understand how to load multiple language files on the server, so that depending on the user, it will provide the correct lang

my init is like this (which must be wrong)
// initialize internationalisation
i18n.use(i18nextMiddleware.LanguageDetector).use(FilesystemBackend).use(sprintf) .init({
   lng: undefined,  // is this OK ?
    debug: true,  // I don't see any debug
    fallbackLng: 'it-IT',
    load:['it','fr','en','fr-FR','en-GB','en-US'],  // THIS MUST BE WRONG
    backend: {
        loadPath: __dirname + '/locales/{{lng}}/{{ns}}.json',  // this is OK it -IT is loaded
        addPath: __dirname + '/locales/{{lng}}/{{ns}}.missing.json',
        jsonIndent: 2
    },
    ignoreRoutes: ['img/', 'public/','css/', 'js/'],    useCookie: true
});

the debugger shows that the IT lang is loaded successfully. But none of the others, I tried : preload:true
but the server crashes,
i18next/bin/index.js:2
<0&&n.push(e)})};r(t.language),t.options.preload&&t.options.preload.forEach(fu
                                                                    ^
TypeError: undefined is not a function

which must be because my list of lang is wrongly defined.
Could you tell me how to put it correctly ?
thanks

**Comment by jamuhl** [comment]
load can take: 'all', 'current' or 'languageonly' --> http://i18next.com/docs/options/#init-options

what you search is preload: lngsArray

**Comment by prtome** [comment]
Thank you!. Now I can see (since I have debug:true) that all my JSON files with the language are loaded.
In my login route I check the lang of the user as it is defined in the database.
My user speaks french, but the db primary lang is italian, and my fallback lang is italian.
I have this in the route.
    var i18n = req.i18n;
    var LNG = req.language;
    var LNGS = req.languages;
(then i define the session.lang)
console.log("LNG",lng,"LNGS",lngs,"SES",req.session.lng)
---> this is : 

LNG: it-IT LNGS: [ 'it-IT', 'it' ] session.lang fr-FR

I don't understand why  LNGS sees only the italian ?, I thought it would show the whole lang array ?

Then I have:
          i18n.changeLanguage(user.mylang);

But nothing happens, the server stays in Italian ! what can be wrong in my setting ?

Thanks for your help

**Comment by jamuhl** [comment]
what you mean by the server stays in italian? do you mean i18next instance has still language set to 'it'?

that would be normal. the language is only set to current request - means accessing req.t will use lng set on req.language (set by req.i18n.changeLanguage or detected by the languageDetector coming with this module. which can lookup lng from req.session.lng)

**Comment by prtome** [comment]
you mean after I call req.i18n.changeLanguage(mylang) with mylang set to fr-FR I should see everything in french ?
I must be doing something very wrong somewhere, because I still see all text in italian, the ones in the jade template or the messages coming from the server because of an error.
I am doing : req.i18n.changeLanguage(mylang);
no callback, nothing else. is that OK ? or I am wrong here and that is why it does not work ?
thanks a lot

**Comment by prtome** [comment]
sorry if I ask many questions, there is obviously something I don't get correctly
If my init is
i18n
  .use(i18nextMiddleware.LanguageDetector)
  .use(FilesystemBackend)
  .use(sprintf)
  .init({
   lng: undefined,
    debug: true,
    load:'all',
    fallbackLng: 'it-IT',
    backend: {
        loadPath: __dirname + '/locales/{{lng}}/{{ns}}.json',
        addPath: __dirname + '/locales/{{lng}}/{{ns}}.missing.json',
        jsonIndent: 2
    },
    preload:['it','fr','en','fr-FR','en-GB','en-US'],
    ignoreRoutes: ['img/', 'public/','css/', 'js/'],
    useCookie: true
});

i was expecting that req.languages would be ['it-IT',fr-FR','en-GB','en-US'],
and not just ['it-IT']
 i can see the all languages files have been read in the log, but not loaded ? why ? 

thanks again

**Comment by jamuhl** [comment]
req.i18n.changeLanguage(user.mylang); needs no callback -> uses getFixedT under the hood: https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L26

req.languages should be ['fr-FR', 'fr', 'it-IT] but there is currently an issue - i don't reset req.languages after changeLanguage is called (but req.languages is only to show which order translation for that user will be lookedup - not more)

**Comment by prtome** [comment]
Thanks, so I should not look at req.languages then. Ok
Now still with the same init as before, I see in the log that all language files have been read correctly (it shows them).
In ly login route I get the session lang for the user, which might be different from the database lang
I have:
         console.log("BEFORE CHANGE LNG",req.language,"SESSSION LANG",req.session.lng)
          i18n.changeLanguage(user.mylang);
        console.log("AFTER CHANGE LNG",req.language,"SESSSION LANG",req.session.lng)

and in the log:

     BEFORE CHANGE LNG it-IT SESSSION LANG en-GB
    AFTER CHANGE LNG it-IT SESSSION LANG en-GB
req.language is always it-IT -> this is normal?

in my route I call the error megs as : req.i18n.t('error.msgerr')     
I get them in italian always

my jade templates have the text as =t('key.value')
I get them in italian

while my Jquery code has the correct translation (I pass the lang to the page in the template, and it is correct).

I have controlled my code to make sure I don't have italian hard coded somewhere, and no.

**Comment by prtome** [comment]
I think I found out  - I did not understood that I must call i18n.changeLanguage(user.mylang);  before rendering each of my pages ? it seems that req.lng is not kept and switches back to italian (maybe because I am in Italy?)

before change lang:  req.language=it-IT dbLanguage=en-GB req.lng=it-IT
after change lang:  req.language=it-IT dbLanguage=en-GB req.lng=en-GB

the login page ( a jade template) is presented correctly in english
user enters name. password and click login
in the login routebefore changeLang :
req.language=it-IT req.lng=it-IT user.lang=en-GB
after changeLang
req.language=it-IT  req.lng=en-GB user.lang=en-GB

where does req.lng come from ? my browser is in english, my system is in english,  I am in Italy
Thanks for your help

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L17

if you use: https://github.com/i18next/i18next-express-middleware#language-detection from the language detection you define.

else it uses the fallback language and expects you to set it on every request.

**Comment by jamuhl** [comment]
closing
