### ISSUE TITLE
Fetching languages at every request

### ISSUE THREAD

**Issue by fenos** [i18next/i18next-express-middleware#142]
Hi There, 

Firstly, thanks for the fantastic toolset that **i18Next** provides.

I'm seeing a weird behaviour on my app, (explained below). 

I'm server rendering my React app and that works great.
I'm using this express middleware to fetch the languages from a remote server then hydrating the client with the current language object.

However once i start the frontend server if **any of my translations changes** on the remote server it seem that the middleware **doesn't re-fetch** the translations that it already loaded on a different request. 

This is my middleware on the `frontend server`

**middleware/i18.js**
```js
// Middleware
import i18next from 'i18next';
import Backend from 'i18next-node-remote-backend';

const middleware = require('i18next-express-middleware');

const baseUrl = process.env.SERVER_API_GATEWAY_URL;
i18next
  .use(middleware.LanguageDetector)
  .use(Backend)
  .init({
    fallbackLng: 'en',
    preload: ['en'],
    debug: true,
    ns: ['common', 'validations'], // <-- Note i want i18 to preload this 2 namespaces
    defaultNS: 'common',
    backend: {
      loadPath: `${baseUrl}/locales/resources.json?lng={{lng}}&ns={{ns}}`,
      addPath: `${baseUrl}/locales/add/{{lng}}/{{ns}}`,
      allowMultiLoading: true,
    },
  });

export default (options = {}) => {
  return middleware.handle(i18next, {
    removeLngFromUrl: false,
    ...options,
  });
};
```

used like that:

```js
app.use(
  assets(),
  i18(),
  ssr(),
);

app.listen(SSR_SERVER_PORT, () => {
  console.log(`Server Listening at port: ${SSR_SERVER_PORT}`);
});
```

If my frontend server get restarted then a new request get issued and I can see my translation been reflected. 

Can you please advice on what i'm doing wrong or if could be a potential bug? Thanks!

**Comment by jamuhl** [comment]
That's expected behaviour...we do not reload translations on every request.

you can do a forces reload on interval using https://www.i18next.com/api.html#reloadresources

**Comment by fenos** [comment]
Ok thanks for clarifying that 👍  however would it sound like a feature that the middleware could offer as an option? example:

```
return middleware.handle(i18next, {
   refreshInterval: 2000, // 2 seconds keep in memory then re-fetch
});
```

Where this option could have few behaviours:

when is set to `0`: same behaviour as now keep in memory all the time ( default value )
when is set to more then `0` ex `2000` keep in memory for max `2` seconds then re-fetch
when is set to `false`: always re-fresh ( this option is very useful in development )

If you agree that is a good idea I can make a PR 👍

**Comment by jamuhl** [comment]
why not...open for it ;)

We already did something similar for the locize.com backend: https://github.com/locize/i18next-node-locize-backend/blob/master/src/index.js#L46

**Comment by fenos** [comment]
Fantastic, will try to do something about it! 
However do you think the logic should live in the `connector` or in the `middleware` would be just fine? 😄

**Comment by jamuhl** [comment]
if possible i would place that in the backend implementation

**Comment by fenos** [comment]
Pr ready:

https://github.com/i18next/i18next-node-remote-backend/pull/4

**Comment by jamuhl** [comment]
PR was merged and new version published...thank you for taking the time to provide it.
