### ISSUE TITLE
lng is being detected and returned as an array

### ISSUE THREAD

**Issue by fetimo** [i18next/i18next-express-middleware#147]
Hi,

I think [this commit](https://github.com/i18next/i18next-express-middleware/commit/5526cf5230514ae99f99d8dafb29db4685f761f6#diff-c3f9df416cf0dcc09559dd2941c7b763) has caused a regression. It allows the lng to be set to an array instead of a string, which at the time of writing causes the main i18next package to [trip up as it's trying to call `toLowerCase` on an array](https://github.com/i18next/i18next/blob/e8b6e45e6d1bc696f7800f10212a5cb27c19a893/src/i18next.js#L129).

I'm using:

"i18next": "^10.5.0",
"i18next-browser-languagedetector": "^2.1.0",
"i18next-express-middleware": "^1.1.0",
"i18next-localstorage-cache": "^1.1.1",
"i18next-node-fs-backend": "^1.0.0",
"i18next-xhr-backend": "^1.5.1"

Thanks, let me know if more information is needed to reproduce the issue.

**Comment by jamuhl** [comment]
should be fixed in 18next-express-middleware@1.1.1
