### ISSUE TITLE
Set cookie on each request

### ISSUE THREAD

**Issue by nanom1t** [i18next/i18next-express-middleware#149]
Hi,

I'm using i18next in my express.js application and it works great. However I've noticed that i18next-express-middleware (or other related package) set lookup cookie on each request (with AJAX requests too) even when request headers already have cookies. 

Dependencies:
```
 "i18next": "^11.3.1",
 "i18next-express-middleware": "^1.1.1",
 "i18next-node-fs-backend": "^1.0.0",
 "i18next-sync-fs-backend": "^1.1.0",
```
Configuration:
```
var i18next = require('i18next');
var i18nextFsBackend = require('i18next-sync-fs-backend');
var i18nextMiddleware = require('i18next-express-middleware');

var options = {
    //debug: configs.APP_DEBUG,
    initImmediate: false,
    whitelist: configs.LOCALIZATION_LOCALES,
    preload: configs.LOCALIZATION_LOCALES,
    fallbackLng: configs.LOCALIZATION_LOCALE_DEFAULT,
    ns: ['common', 'labels'],
    defaultNS: ['common', 'labels'],
    load: 'current',
    saveMissing: true,
    saveMissingTo: 'current',
    backend: {
        loadPath: configs.APP_PATH + '/../configs/locales/{{lng}}/{{ns}}.json',
        addPath: configs.APP_PATH + '/../configs/locales/missing/{{lng}}-{{ns}}.json',
        jsonIndent: 4
    },
    detection: {
        order: ['querystring', 'cookie', 'header'],
        lookupCookie: 'lang',
        lookupQuerystring: 'lang',
        cookieExpirationDate: new Date(Date.now() + configs.LOCALIZATION_LOCALE_TTL),
        cookieDomain: configs.APP_DOMAIN,
        caches: ['cookie']
    },
    ignoreRoutes: ['/api/']
};

i18next
    .use(i18nextMiddleware.LanguageDetector)
    .use(i18nextFsBackend)
    .init(options);

module.exports = {
    i18next: i18next,
    route: i18nextMiddleware.getResourcesHandler(i18next),
    middleware: i18nextMiddleware.handle(i18next, {}),
    missing: i18nextMiddleware.missingKeyHandler(i18next)
};
```
It is not a critical bug for me, but I've enabled caching for language detector(`caches: ['cookie']`). Is it expected behavior to set lookup cookie on each request or I'm doing something wrong?

Thanks

**Comment by jamuhl** [comment]
it's expected behaviour as i do not know if this is the first request. Setting caches will result in sending lng in cookies so lng goes back to browser and will be sent again from browsers i18next instance.

**Comment by jamuhl** [comment]
PR for extra treatment via options would be accepted.

**Comment by nanom1t** [comment]
Thank you for the response.

It is not the first request. In each request I already have `lng` (`lang` in my case) param in cookies and I'm not changing language (`req.i18n.changeLanguage`) on the backend. But the cookies are setting on each request.
![screen shot 2018-05-13 at 11 21 32 am](https://user-images.githubusercontent.com/6481192/39965891-8e76ceaa-56aa-11e8-9820-1205ee212678.png)

**Comment by nanom1t** [comment]
Ok. Thank you.
