### ISSUE TITLE
How to redirect non localized url to localized?

### ISSUE THREAD

**Issue by joelamltc** [i18next/i18next-express-middleware#150]
as above, i want my app for every not localized url like
```
'/', '/about-us', '/contact-us'
```
to be redirected to 
```
'/en', '/en/about-us', '/en/contact-us'
```
thx

**Comment by jamuhl** [comment]
not part of the middleware....you need to create an own middleware for express checking for routepath contains locale - if not res.redirect to route having i18next.languages[0] as first route segment

**Comment by jamuhl** [comment]
you might need to take the one on request (req.i18next)...not the global instance

**Comment by nagman** [comment]
**req.i18n.languages** gives me a strange array. It contains all the parts of the path.

If I query `/en/` => `[ 'en' ]`
If I query `/pricing/` => `[ 'pricing', 'fr' ]` (where 'fr' is the default language)

**Comment by nagman** [comment]
Just saw this: https://github.com/i18next/react-i18next/issues/475#issuecomment-404543041

In fact, I need to specify a whitelist.
It keeps only the specified prefixes in `req.i18n.languages`

**Comment by jamuhl** [comment]
yes....whitelist should do the trick not getting pricing accepted as a language ;)

**Comment by jamuhl** [comment]
closing this for now - if still relevant feel free to reopen
