### ISSUE TITLE
Why i18next and language cookies can have different values ?

### ISSUE THREAD

**Issue by acmoune** [i18next/i18next-express-middleware#152]
I am trying to do SSR.
on the client side I put this settings

```javascript
detection: {
    caches: ['localStorage', 'cookie']
}
```

Server side: 

```javascript
detection: {
    caches: ['cookie']
}
```

But it seems like the modules (**i18next-express-middleware** and/or **i18next-browser-languagedetector**) are creating two cookies on browsers: `i18next` and `language`, and they can have different values. 

I removed `fallbaclLng` and `whitelist` from my settings, so the language I find in `i18next ` cookie is `dev`, but the one in `language` cookie is `en-US`. Why ?

The big issue I have now is that, when I get the language from a server route handler, through `request.i18n.language`, under `firefox`, the detector return `dev`, so it seems to read from the `i18next `cookie, but on Chrome it return `en-US`, so it seems to read from `language` cookie.

So I am asking myself if those two cookies should not always have the same value ?

**Comment by jamuhl** [comment]
Cookie are the same if not configured different:

https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js#L12

https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/index.js#L14

**Comment by acmoune** [comment]
I think I am starting to see the problem. The route in question is an API route. May be that on firefox, the cookies are sent with the request, while on chrome I might have to insert the lng in the header or something ?

**Comment by acmoune** [comment]
When I run this from my API route handler:

`console.log(req.cookies)`

On firefox I have this
`{ i18next: 'dev', language: 'en-US' }`

On chrome I have this
`{ language: 'en-US' }`

???

**Comment by acmoune** [comment]
Adding the credential option to fetch fixed it:

`fetch(url, { credentials: 'same-origin' })`

Thanks.
