### ISSUE TITLE
exclude /examples/.../node_modules/* directories from published module

### ISSUE THREAD

**Issue by tanyaYourchuck** [i18next/i18next-express-middleware#156]
From 1.2.1 to 1.3.1 the module size went from 9 KB to > 4,000 KB. 
Presumably the huge bump in size of 1.3.1 is due to bunch of node_modules directories embedded into examples:
/examples/basic/node_modules/*
/examples/basic-handlebars/node_modules/*
/examples/basic-pug/node_modules/*

I only noticed because I ran into issues with filepath limits since the node_modules got nested so deep.

**Comment by jamuhl** [comment]
i18next-express-middleware@1.3.2 should fix this. Thank you for reporting.
