### ISSUE TITLE
Conceptual approach for i18n with Express API

### ISSUE THREAD

**Issue by senser1** [i18next/i18next-express-middleware#160]
Hi,

I'm having some trouble figuring out what a reasonable approach is for the following;

Frontend: React frontend application using react-i18next with local JSON translations. Current translation is stored in a cookie. 
Backend: Express REST API (so stateless). I've setup i18next with i18next-express-middleware and language detection based on the cookie set client side. In my controller I get the current language on the reques object, so far all clear. However, I would like to translate some data retrieved on the backend from another resource, translate some parts of it and pass this data to the frontend. However, because I cannot cache / persist the language (right?) I have to pass in the i18n object on the request several layers deep from the controller, to my business logic to the function that eventually translates the data based on the language the user selected. 

Am I missing something obvious here? Is this the correct way?

**Comment by jamuhl** [comment]
no it's correct - either pass down req.i18n or at least req.lng and use that on main instance as `i18next.t('myKey', { lng: req.lng });`

**Comment by senser1** [comment]
Thanks. I noticed that passing the language via the query string does not actually change req.language. I have to manually call the changeLanguage method on the i18n instance to actually change it. Language detecting via de cookie works fine. Is this by design?

**Comment by jamuhl** [comment]
hm...no...it should handle that detection from querystring: https://github.com/i18next/i18next-express-middleware#detector-options (?lng=en)

**Comment by senser1** [comment]
A night of sleep and reimplementing the querystring lookup in the detector options and it now works fine. Can be closed.
