### ISSUE TITLE
Importing t() from i18next (instead of from request) is resulting in error "Cannot read property 'translator' of undefined"

### ISSUE THREAD

**Issue by senser1** [i18next/i18next-express-middleware#161]
I've setup i18next with the express-middleware package. Everything works fine with translating strings with the `lng` and `t()` function from the request object. However if I import it from the i18next instance itself, I get the error `"Cannot read property 'translator' of undefined"` when calling `t()` with my own language string (not importing that from i18next, just passing it in hardcoded).

A console.log(i18next) learns that the import works, I also have a `t()`, it only not works. The use case for this: i'm having a business layer that data fetching and transformations (like translations) and when doing a business layer to business layer call, I not always have the request object available.

**Comment by jamuhl** [comment]
try the use not importing `t` but using i18next.t

**Comment by senser1** [comment]
Thanks for the quick follow up. You mean not importing from the i18next instance but directly from the i18next module?

**Comment by jamuhl** [comment]
idk...never used the middleware or i18next with imports on node.js -> so not sure how that works out in the end.

just guess `import { t } from 'i18next'` might work not as expected - but like said...idk

but using `i18next.t` from some `var i18next = require('i18next')` should work

**Comment by jamuhl** [comment]
somewhere you add i18next to the middleware:

app.use(
  middleware.handle(i18next, {
    ignoreRoutes: ["/foo"],
    removeLngFromUrl: false
  })
);

just use i18next.t on that i18next -> should work (the one instance you init)

**Comment by senser1** [comment]
I understand what you mean, I actually did that, but that does result in the error `Cannot read property 'translator' of undefined"`. The t() function is actually being called, but somehow not with the same outcome as calling the t() on the request object.

**Comment by senser1** [comment]
You are right :)

Setting the t() function like this does work correctly;
`return { lng: 'en', t: i18next.t.bind(i18next) };`

**Comment by plxel** [comment]
@senser1 could you provide an example?
I'm trying to use i18n instance t function without request object, but it looks like it has no access to loaded locales, because it just returns keys as they are

**Comment by jamuhl** [comment]
@plxel sounds like you call `t` before init call is done...did you wait until callback of init is called before calling that t function ?

**Comment by plxel** [comment]
@jamuhl I thought about it
But I tried to use instance inside my resolver, which also has access to req object, and req.i18n.t works fine

**Comment by jamuhl** [comment]
try calling `t` with a lng (main instance has no lng set as using the main global instance will collide with other user requests) -> `i18n.t(key, { lng: 'de' });`

**Comment by plxel** [comment]
@jamuhl 
ok, looks like if I call it inside of my resolver i18n.t(key, { lng: 'ru' }) it translates this correctly, but I put 'en', it still not working and also creates missing.json file for that key, despite the translation.json is present

Also I tried to force change language on server start using `changeLanguage` to `en`. After that I just see that `language` and `languages` properties are set to `en` on i18n instance (before that it was undefined), but still it is not translating the key.

Also, if it uses global instance, is there a way to use i18n instance outside of scope where req is defined? without hardcoding lng parameter, so that it uses the current language

**Comment by plxel** [comment]
I found in source, that middleware uses cloneInstance, so if I need to sync instances I have to to do it manually somehow

**Comment by jamuhl** [comment]
that's because request are async in nodejs -> any colliding request on same time would interfere with each other -> so every request gets it's own instance with set language correctly detected for that request.

**Comment by plxel** [comment]
@jamuhl ok, thanks
I will try to figure out how it's better to organise my code then
