### ISSUE TITLE
Incomplete language detection

### ISSUE THREAD

**Issue by pcwiek** [i18next/i18next-express-middleware#164]
Versions:
```
i18next-express-middleware@1.5.x:
  version "1.5.0"

i18next@11.10.x:
  version "11.10.2"
```

I'm not sure what's going on here, because I'm pretty sure it should _just work_, but it seems the `req.languages` gives 'incomplete' results by just returning the selected 'most matching' language and fallback.

Here's the set up:
```
accept-language: da,sk,es
```

and
```
i18next.use(middleware.LanguageDetector).init({
    detection: {
        order: ['header', 'querystring', 'cookie']
    },
    lowerCaseLng: true,
    fallbackLng: 'en'
});
// and of course middleware.handle(i18next) is plugged in
```

now the result of https://github.com/i18next/i18next-express-middleware/blob/796a85b2feb91f6a7d8ee14c34ae52c107be6efd/src/LanguageDetector.js#L55
is what I would generally expect:
`[ 'da', 'sk', 'es'] `

but then for some reason on the request itself in my domain handler:
```
req.language
> 'da'
req.languages
> ['da', 'en']
```
While I'd rather expect to see:
```
req.languages
> ['da', 'sk', 'es', 'en']
```

I _think_ it's right here:
https://github.com/i18next/i18next-express-middleware/blob/796a85b2feb91f6a7d8ee14c34ae52c107be6efd/src/index.js#L22-L27
since that will pick the 'most closely matching' language and extract the language code from it, if applicable, so from the example above we'll just get `['da']`. If I pass `da-DK` instead of just `da`, the final `req.languages` collection is `['da-dk', 'da', 'en']` - while I'd reckon it should be `['da-dk','da','sk','es','en']`.

Anyway, after browsing the older tickets in both this repo and main i18next repo I'm pretty sure it should work the way I expect, but for some reason it doesn't ❔ 

----
Easy, quick & dirty repro in REPL:
```javascript
var i18next = require('i18next');
var middleware = require('i18next-express-middleware');
i18next.use(middleware.LanguageDetector).init({ detection: { order: ['header', 'querystring', 'cookie'] }, lowerCaseLng: true, fallbackLng: 'en' });
var handler = middleware.handle(i18next);
var req = { headers: { 'accept-language': 'da,es,sk'}};
handler(req, { set() {} }, () => console.log('Done called'));
req.languages;
```

Result:
```
[ 'da', 'en' ]
```

**Comment by jamuhl** [comment]
"sadly" this is expected behaviour. Current implementation will return one language from detection and the req.languages is what i18next will look at to find a value for given key.

Not sure how hard it would be to extend https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L84 to support multiple languages...and as headers is only detection function giving an array for languages with priorities i'm also not sure it's worth the added complexity?!??!?

**Comment by pcwiek** [comment]
Ah, that's slightly disappointing. That's because if a user requests multiple locales with specific priorities, for example: `da;q=0.9,es;q=0.7,en-gb;q=0.6,en;q=0.5`, I'd like to be able to select the most closely matching _available_ content that I have. I might not have it in danish, but it might be available in spanish - and it's not only the i18n asset/resource files, but also domain DB data. Having all languages that are requested would help there...
For the time being, I might hack around a bit and 'override' the `req.languages` property myself in downstream middleware.

**Comment by jamuhl** [comment]
brings to an idea...

first: don't try to hack down req.languages -> that is only used as read...the function to get that `resolveHierarchy` is used everywhere; so changing it on req.languages won't help...

but:

create a own detection function: https://github.com/i18next/i18next-express-middleware#adding-own-detection-functionality

based on: https://github.com/i18next/i18next-express-middleware/blob/master/src/languageLookups/header.js but checking against the list of languages you provide -> so return will be first in prio that is in your array of supported languages

**Comment by jamuhl** [comment]
would even accept a PR adding that to existing detector where you can pass an additional option:

https://github.com/i18next/i18next-express-middleware#detector-options

```js
{
  // order and from where user language should be detected
  order: [/*'path', 'session', */ 'querystring', 'cookie', 'header'],

  // keys or params to lookup language from
  lookupQuerystring: 'lng',
  lookupCookie: 'i18next',
  lookupSession: 'lng',
  lookupPath: 'lng',
  lookupFromPathIndex: 0,

// header whitelist
lookupHeaderSupportedLanguages: ['en', 'de']

  // cache user language
  caches: false, // ['cookie']

  // optional expire and domain for set cookie
  cookieExpirationDate: new Date(),
  cookieDomain: 'myDomain',
  cookieSecure: true // if need secure cookie
}
```

**Comment by pcwiek** [comment]
Hm, interesting, but I have to return all languages and attach them to `req.languages`, even for my domain use - then I can pass the whole locale array to my DB queries, where I do the content selection in the specified order. That means I don't know up front which content item is available in which locale 😉 

So overwriting `req.languages` solves my domain issue problem, but that probably won't play nice with `i18next` assets & resource files... Another option is to hack around and set `fallback` codes to all other locales so that it's all included, but I don't have a good idea right now how to reliably do that.

**Comment by jamuhl** [comment]
yes...for your domain it might work...but for i18next you will have to choose the highest prio language you support and if needed set req.i18next.options.fallbackLng to an array containing all those detected languages...not sure if that works out well.

**Comment by pcwiek** [comment]
@jamuhl yup, that would work! Thanks!
