### ISSUE TITLE
Feature idea: Merge resources for "dialects"

### ISSUE THREAD

**Issue by lucasfeliciano** [i18next/i18next-express-middleware#166]
Currently i18n needs to have one locale per language but these is not optimal since this will lead to duplicated translations.

One thing that we could do is merge the translation files before serving it.

Example:

en.json
```js
const en = {
  "hello": "world",
  "button": "Personalise"
}
```

en_GB.json
```js
const en_GB = {
  "button": "Personalize"
}
```

Then the middlewere would serve
```js
Object.assign({}, en, en_GB)
```

Doing that we just need to translate specific strings and would have a fallback to the "main"  language.

Is there any technical limitation to do that?

**Comment by jamuhl** [comment]
i18next does this basically without merging:

setting language to en-US it will lookup keys in en if not found in en-US -> so en-US has only to contain values different than to en (assuming en is english in british flavor)

**Comment by lucasfeliciano** [comment]
So it needs to be `en-US` instead of `en_US` right?

**Comment by jamuhl** [comment]
yes `en-US`. Just for more details: https://www.i18next.com/principles/fallback#language-fallback

**Comment by lucasfeliciano** [comment]
I'm feeling so bad, because I searched the documentation before open the issues, and I couldn't find it.
🙈 

Sorry for that

**Comment by jamuhl** [comment]
nothing to worry...the documentation while improved over the time still could need a lot of improvement.
