### ISSUE TITLE
Setting 'lng' does not override language detection middleware

### ISSUE THREAD

**Issue by StarpTech** [i18next/i18next-express-middleware#178]
As titled. The n18next [options](https://www.i18next.com/overview/configuration-options#languages-namespaces-resources) should be priotized.

**Comment by jamuhl** [comment]
are you talking about setting language using i18next.changeLanguage?

**Comment by StarpTech** [comment]
No, according to the i18next docs when I pass the `lng` to use the `init` method it should overwrite any language detection mechanism. I think it would be great to respect that setting in the plugin.

**Comment by jamuhl** [comment]
That's not how it works in express - the i18next instance is not shared - there is one per request to make sure there are no issues on async operations where one request toggles the language of a still pending request of another user.

So short...language detection happens per request: https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L40

Either not add a detector if not using it - or "hard code" the language on req.lng in a middleware before the i18next middleware.

**Comment by StarpTech** [comment]
That's correct but I'm looking for a way to enforce a specific language even when a custom language detector is used (e.g to enforce 'en' until the product was released officially without to change code). I think that should be considered [here](https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L40) like

```js

let lng = req.lng || i18nnext.options.lng;
if (!lng && i18next.services.languageDetector) lng = i18next.services.languageDetector.detect(req, res);
```

**Comment by jamuhl** [comment]
for the case set whitelist: 'en' and fallbackLng: 'en' should have same effect.

**Comment by StarpTech** [comment]
Thanks, I will try.
