### ISSUE TITLE
Add optional "lookupHeader" to replace default header 

### ISSUE THREAD

**Issue by Dominic-Preap** [i18next/i18next-express-middleware#179]
Can we have optional "lookupHeader" to replace default header "Accept-Language"?
```js
i18next
      .use(FilesystemBackend)
      .use(i18nextMiddleware.LanguageDetector)
      .init({
        detection: {
          order: ['header', 'querystring'],
          lookupQuerystring: 'lng',
          lookupHeader: 'x-language'
        },       
      });
```

**Comment by jamuhl** [comment]
feel free to provide a PR taking value from options: https://github.com/i18next/i18next-express-middleware/blob/master/src/languageLookups/header.js#L12 and default to the "Accept-Language" if not set

**Comment by Dominic-Preap** [comment]
@jamuhl would you be able to review my PR?

**Comment by Dominic-Preap** [comment]
@jamuhl Would you mind update this option in README.md? Thanks.

**Comment by jamuhl** [comment]
@Dominic-Preap was added to readme - thank you for the reminder...
