### ISSUE TITLE
Fastify compatablity

### ISSUE THREAD

**Issue by TopHatMan** [i18next/i18next-express-middleware#184]
Simple issue res.set causes fastify server to crash. 

I just commented it out and everything works fine. But I am trying to repliment the res.set in fastify way.

**Comment by jamuhl** [comment]
If you come up with a solution to make it work for both PR would be very welcome...else might be a good time to create a i18next-fastify-middleware

**Comment by TopHatMan** [comment]
I was thinking of that for now I just removed the res.set and copied it to my app. I am not using server url translation. I think thats broken now.

**Comment by jamuhl** [comment]
closing due inactivity
