### ISSUE TITLE
Fishy  forEach loop function return on ignored  routes check

### ISSUE THREAD

**Issue by agalazis** [i18next/i18next-express-middleware#19]
In [this](https://github.com/i18next/i18next-express-middleware/blob/v0.3.1/src/index.js#L9) line you use a forEach loop to check if  any of the ignored routes are in the current path. if an ignored route is in the path you call next and return in the function given to forEach. Don't you also want to return from the middle-ware function ? Wouldn't it be better to use a normal for loop and return to stop execution of the middle-ware function ?Why are you returning in the function provided to forEach(what does it add?)?

**Comment by agalazis** [comment]
[Here](https://github.com/agalazis/i18next-express-middleware/blob/05db1ce37f055d8b6e59b5906a8ebf0ccc568861/src/index.js#L8) is my suggestion. If it's good I can do a PR or you can fix it as you prefer.  I look forward to your feedback.

**Comment by jamuhl** [comment]
agree...PR would be very welcome.

**Comment by agalazis** [comment]
@jamuhl  Thank you for the fast feedback :+1: .PR done :)

**Comment by jamuhl** [comment]
published v0.3.2

**Comment by agalazis** [comment]
Thanks a ton!
