### ISSUE TITLE
Missing tag for v1.8.2

### ISSUE THREAD

**Issue by 1337MARCEL** [i18next/i18next-express-middleware#195]
Hi, first of all thanks for writing/maintaining this library 🙂 

Could you please create a new git tag for [`v1.8.2`](https://github.com/i18next/i18next-express-middleware/tags)?

Thank you guys in advance!

**Comment by jamuhl** [comment]
done - just out of curiosity - what do you need it for?

**Comment by 1337MARCEL** [comment]
Thank you!

I think it's very handy to compare between two releases. ([Example](https://github.com/i18next/i18next-express-middleware/compare/v1.8.0...v1.8.2))

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
