### ISSUE TITLE
not sure that this is issue (loadPath from url/database)

### ISSUE THREAD

**Issue by goors** [i18next/i18next-express-middleware#32]
Is there anyway that I can load language from some url /localesdb/:lng for example or db?
Setting this does not work:
<pre>
backend: {
    loadPath: '/localesdb/{{lng}}/',
    //loadPath: './locales/{{lng}}/{{ns}}.json',
    jsonIndent: 2
}, 
</pre>

**Comment by goors** [comment]
Forget this. I will use this as backend:

https://github.com/i18next/i18next-xhr-backend

**Comment by jamuhl** [comment]
you want to use: https://github.com/i18next/i18next-node-remote-backend
