### ISSUE TITLE
localized routes: migration from version 1 to 2 i18next

### ISSUE THREAD

**Issue by zauker** [i18next/i18next-express-middleware#34]
Hello everyone,
I need to have in my app localized path, for example:

    /:lng/part-to-translate-too

    /en/team
    /fr/equipe
    /it/squadra

In version 1 of i18next with i18next-node I used this code:

    
	i18n.init(options, function(t) {
		i18n.addRoute('/:lng/main:pages.team', ['en', 'fr', 'it'], app, 'get', function(req, res) { /*endpoint*/ });
        });

How had to re-write my code using i18next version 2 with i18next-express-middleware ?
Any help is appreciated

**Comment by jamuhl** [comment]
the localized paths are not implemented yet. had no personal need for them:

implementation is rather simple: https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L288

might add this later...right now i'm to hard on time. PR would be great and speed this up.

**Comment by zauker** [comment]
https://github.com/i18next/i18next-express-middleware/pull/39

**Comment by jamuhl** [comment]
thanks for the contribution and making this more awesome.
