### ISSUE TITLE
ES6 imports not working quite right

### ISSUE THREAD

**Issue by bkbrooks** [i18next/i18next-express-middleware#37]
Hello,

I've been experiencing an issue when trying to import the express middleware in my project. 

This works totally fine:
```
var middleware = require('i18next-express-middleware')
app.use(middleware.handle(i18n))
```

This works fine too:
```
import { LanguageDetector } from 'i18next-express-middleware'

i18n
  .use(Backend)
  .use(LanguageDetector)
  .init({})
```

However if I import the whole package with ES6, it breaks. 
```
import middleware from 'i18next-express-middleware'
app.use(middleware.handle(i18n))
```

I get the error: 
```
app.use(_i18nextExpressMiddleware2.default.handle(_i18n2.default));                                          
TypeError: Cannot read property 'handle' of undefined
```

**Comment by jamuhl** [comment]
import { handle } from 'i18next-express-middleware'
app.use(handle(i18n))

**Comment by bkbrooks** [comment]
Yeah, that works too, but shouldn't it be able to be imported as a whole module? In either case, it's a minor issue, just thought I should bring it up.

**Comment by jamuhl** [comment]
we might add a export default - will do that for a next version.

**Comment by jamuhl** [comment]
v0.4.0 should have an export.default exporting complete module as object, named function exports still available.

**Comment by henryhuang** [comment]
it works for me: 

import i18nMiddleware, { LanguageDetector } from 'i18next-express-middleware';
