### ISSUE TITLE
Using together with sprintf postprocessor and overloadTranslationOptionHandler

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next-express-middleware#4]
I'm trying to get interpolations to work in `i18next 2.0`, in the browser I found no issue, but in `express` the following won't work:

```javascript
i18next.t('interpolationTest1', 'foo');
```
even when you have 

```javascript
i18next.init({
  overloadTranslationOptionHandler: sprintf.overloadTranslationOptionHandler
});
```
set.

The problem is here:

```javascript
    // assert t function returns always translation
    // in given lng inside this request
    let t = function(key, options) {
      options = options || {};
      options.lng = options.lng || req.lng;
      return i18next.t(key, options);
    };
```

in `src/index.js` in this repo, lines 20-26. Trying to set `options.lng` throws the following error

```
Unhandled rejection TypeError: Cannot assign to read only property 'lng' of foo
```

I'd make a pull request fixing this, seeing as the obvious fix is to use `options.overloadTranslationOptionHandler` to transform the options object, but I thought I'd confirm with you first :)

**Comment by jamuhl** [comment]
yes...should solve it...PR would be welcome.

**Comment by perrin4869** [comment]
I'll put together a PR tomorrow then :)

**Comment by perrin4869** [comment]
PR sent

**Comment by perrin4869** [comment]
Actually though, thinking about it more carefully, it might not be the best solution, because you run the risk of running `overloadTranslationOptionHandler` twice, once in the middleware translate and one in `i18next.t` down the line... right now it works fine though

**Comment by jamuhl** [comment]
don't think it will hurt. as `i18next.t` will not receive a non object anylonger so it will step over. the t function in req will transform correctly...will be merged and published asap.

**Comment by perrin4869** [comment]
My concern is, what if you want to define an `overloadTranslationOptionHandler` that works over an `object`... unlikely, and I don't see any practical reason why you might wanna do it, true, but still theoretically possible

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/src/Translator.js#L47 overloadOptions might be a little misleading naming...is more a overloadArgumentsToOptions ;) the overload gets only triggered if options is not an object - calling t with different arguments then t(key, opts)

**Comment by jamuhl** [comment]
sample t(key, defaultValue) -> default
or sprintf stuff

**Comment by jamuhl** [comment]
0.0.17 published
