### ISSUE TITLE
How to fallback on default language for unsupported language

### ISSUE THREAD

**Issue by nicolas-moteau** [i18next/i18next-express-middleware#40]
Hello
I have an app with 2 supported languages 'fr' and 'en'.
Is there a way to configure a fallback for any other detected language?

If not yet, the following should be nice to use:

```js
var i18next = require('i18next');
var middleware = require('i18next-express-middleware');

i18next
	.use(middleware.LanguageDetector)
	.init({
		fallbackLng: ['en'],
		detection: {
			order: ['querystring'],
			
			// unavailable but nice to have option 
			supportedLanguages: ['fr', 'en'],
			
			// keys or params to lookup language from
			lookupQuerystring: 'lng',

			// cache user language
			caches: false, // ['cookie']
		}
	});
```

`http://server:port/lng=fr  	-> req.language is 'fr'` 

`http://server:port/     	-> req.language is 'en' (fallbackLng)`

`http://server:port/lng=zzz 	-> req.language should be 'en' (fallbackLng) since 'zzz' is not in supportedLanguages`

**Comment by jamuhl** [comment]
does it not work? should work like this.

**Comment by nicolas-moteau** [comment]
I doesn't work.
Actually, I don't see `supportedLanguages` as an option in Language detectors, and `supportedLngs` is no more part of i18next v2 options.
Well, may be the problem is with i18next, not i18next-express-middleware?

**Comment by jamuhl** [comment]
ah...yes...it's not supported it's whitelist on i18next:  http://i18next.com/docs/options/#init-options

**Comment by nicolas-moteau** [comment]
Thank you @jamuhl ! This is what I was looking for.

The working code with `whitelist` on i18next options:
```js
var i18next = require('i18next');
var middleware = require('i18next-express-middleware');

i18next
    .use(middleware.LanguageDetector)
    .init({
        fallbackLng: ['en'],

        whitelist: ['fr', 'en'],

        detection: {
            order: ['querystring'],

            // keys or params to lookup language from
            lookupQuerystring: 'lng',

            // cache user language
            caches: false, // ['cookie']
        }
    });
```
And now 
`http://server:port/lng=zzz -> req.language is 'en' (fallbackLng) since 'zzz' is not in whitelist`
