### ISSUE TITLE
express Jade - issue with localization in Jade file.

### ISSUE THREAD

**Issue by Laro88** [i18next/i18next-express-middleware#58]
Translation, including save of missing is fine in serverside .js files, however the Jade translation appears broken, and I am suspecting a config issue without being able to nail it :-(

```
  > 32|           p.small #{t('login.cookietext')};
    33|           p.small (sets a "remember" cookie on your disk - this is the ONLY cookie we use!)

t is not a function
    at eval (eval at <anonymous> (C:\N\yadayata....\node_modules\jade\lib\index.js:218:8), <anonymous>:1235:43)
    at eval 
```
var i18nextMiddleware = require('i18next-express-middleware'); is initialized with session and cookie only, no warnings or errors given there.

I have tried a lot of combinations without any luck.

**Comment by jamuhl** [comment]
do you add the middleware handler?

```
app.use(middleware.handle(i18next, {
  ignoreRoutes: ["/foo"],
  removeLngFromUrl: false
}));
```

**Comment by Laro88** [comment]
Yes, I have it at the very end, tried w and wo params.
```
//app.use(i18nextMiddleware.handle(i18next)); // expose req.t with fixed lng
app.use(i18nextMiddleware.handle(i18next, {
    ignoreRoutes: ["/foo"],
    removeLngFromUrl: false
}));
```
Translation is fine in .js, I get the expected output from this simple lookup, and missing translations are written back to .missing.json
```
var _tlayout = i18next.t("layout:locale");
```
Anything suspicious here?
![i18next](https://cloud.githubusercontent.com/assets/12495700/14450499/30176fc8-007f-11e6-9be8-30b72caeaac1.png)

**Comment by Laro88** [comment]
I had it - but unfortunately I had it too late. Things are almost fine now.

**Comment by jamuhl** [comment]
feel free to reopen if still any issue open.
